export const ADD_ITEM = 'ADD_ITEM';
export const NAME_ITEM = 'NAME_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const CHECKBOX_CLICKED = 'CHECKBOX_CLICKED';
export const GET_AXIOS_LIST = 'GET_AXIOS_LIST';
export const ADD_DEFAULT_TO_STATE = 'ADD_DEFAULT_TO_STATE';